# Generated by Django 4.2.7 on 2023-11-15 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_ens', models.BooleanField(default=False)),
                ('is_adj', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('code_colis', models.AutoField(primary_key=True, serialize=False)),
                ('nom_clt', models.CharField(max_length=255)),
                ('gouvernement', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('adresse_clt', models.TextField()),
                ('tel_clt', models.CharField(max_length=15)),
                ('tel_clt2', models.CharField(blank=True, max_length=15, null=True)),
                ('des', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('nb_article', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('mode_paiement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id_depot', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('num_tel', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('code_etat', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expediteur',
            fields=[
                ('code_expediteur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_expediteur', models.CharField(max_length=255)),
                ('num_tel_expediteur', models.CharField(max_length=15)),
                ('gouvernement', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=255)),
                ('code_tva', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mode_paiement', models.CharField(max_length=255)),
                ('frais_livraison', models.FloatField()),
                ('frais_retour', models.FloatField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('code_reclamation', models.AutoField(primary_key=True, serialize=False)),
                ('type_reclamation', models.CharField(max_length=255)),
                ('etat_reclamation', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('date', models.DateField()),
                ('code_colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colis')),
            ],
        ),
        migrations.CreateModel(
            name='RecetteExpediteur',
            fields=[
                ('code_recette', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_expediteur', models.FloatField()),
                ('montant_societe', models.FloatField()),
                ('nb_colis_livre', models.IntegerField()),
                ('nb_colis_retour', models.IntegerField()),
                ('code_expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expediteur')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('code_livreur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_livreur', models.CharField(max_length=255)),
                ('num_tel', models.CharField(max_length=15)),
                ('frais_livraison', models.CharField(max_length=255)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.depot')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtatColis',
            fields=[
                ('code_etat_colis', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('commentaire', models.TextField()),
                ('code_colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colis')),
                ('code_etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etat')),
                ('code_livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livreur')),
            ],
        ),
        migrations.AddField(
            model_name='colis',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expediteur'),
        ),
    ]
