# Generated by Django 4.2.7 on 2023-11-24 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
