# Generated by Django 4.2.7 on 2023-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_colis_commentaire_alter_etatcolis_code_livreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediteur',
            name='code_expediteur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
