# Generated by Django 4.2.7 on 2023-12-05 23:49
from django.db.models import F

from django.db import migrations, models
def populate_code_barre(apps, schema_editor):
    Colis = apps.get_model('api', 'Colis')
    Colis.objects.filter(code_barre__isnull=True).update(code_barre=F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expediteur_code_expediteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='code_barre',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),        migrations.RunPython(populate_code_barre),

    ]
